# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'httpTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for httpTest
  pod 'Alamofire', '~> 4.5'

  target 'httpTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'httpTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
